---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: no
    update_cache:       yes
    cache_valid_time:   86400
  with_items:
    - fail2ban

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ fail2ban_root_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - fail2ban.local
    - jail.local
  notify: restart fail2ban
  tags: fail2ban_config

- name: ensure default log files exist (for default jails)
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 0644
  with_items:
    -  /var/log/auth.log
  changed_when: no

- name: service start
  service:
    name:  "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - fail2ban
