---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
  - fail2ban

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ fail2ban_root_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - fail2ban.local
    - jail.local
  notify: restart fail2ban

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - fail2ban
